<?php

$artists = [
  '5.5 designers',
  'Abdul Rahman Katanani',
  'Abraham Poincheval',
  'Adalberto Mecarelli',
  'Aglae Liberaki',
  'Agustín Cárdenas',
  'Ai Kitahara',
  'Aiko Miyawaki',
  'Airan Kang',
  'Alain Domagala',
  'Alain Fleischer',
  'Alain Jacquet',
  'Alain Kirili',
  'Alain Mila',
  'Alain Séchas',
  'Albert Ayme',
  'Aleksey Sorokin',
  'Alexander Calder',
  'Alexander Slima',
  'Alexandra Engelfriet',
  'Alexandre Gherban',
  'Alfred Manessier',
  'Alicia Framis',
  'Alighiero Boetti',
  'Allan Mccollum',
  'Amandine Guruceaga',
  'Andrea Blum',
  'Andreas Brandolini',
  'André Barelier',
  'André Borderie',
  'André Nallet',
  'André Raffray',
  'Andy Goldsworthy',
  'Ange Leccia',
  'Angela Bulloch',
  'Angela Detanico',
  'Anish Kapoor',
  'Anita Molinero',
  'Anna-Monika Jost',
  'Anne Deguelle',
  'Anne et Patrick Poirier',
  'Anne Poirier',
  'Anne Rochette',
  'Anne-Marie Pochat',
  'Annick Sterkendries',
  'Ant Farm',
  'Anthony Caro',
  'Anthony McCall',
  'Antoine Bourdelle',
  'Antoine D\'Agata',
  'Antoine Marquis',
  'Antoine Poncet',
  'Antoni Tàpies',
  'Antonin Sorel',
  'Antonio Semeraro',
  'Antoniucci Volti',
  'Antony Gormley',
  'Arcelli Amandine',
  'Arman',
  'Armin Schubert',
  'Arnaud Rochard',
  'Artiste inconnu',
  'Atelier Van Lieshout',
  'ATILA',
  'Auguste Rodin',
  'Aung Ko',
  'Aurèle',
  'Aurélie Ferruel',
  'Aurélie Nemours',
  'Ay-O',
  'Ayse Erkmen',
  'Aï Kitahara',
  'Baltasar Lobo',
  'Barbara Kruger',
  'Beat Lippert',
  'Beat Streuli',
  'Ben',
  'Ben Jakober',
  'Benjamin Boré',
  'Benoit Tremsal',
  'Benoît-Marie Moriceau',
  'Bernar Venet',
  'Bernard Alleaume',
  'Bernard Dejonghe',
  'Bernard Lassus',
  'Bernard Lorjou',
  'Bernard Pagès',
  'Bernard Piffaretti',
  'Bernard Tschumi',
  'Bert Theis',
  'Bertrand Dezoteux',
  'Bertrand Lavier',
  'Bertrand Planes',
  'Bertrand Vivin',
  'Bevis Martin',
  'BGL',
  'Bili Bidjocka',
  'Bill Culbert',
  'Bill Fontana',
  'Bjørn Nørgaard',
  'Bless',
  'Bong-gi Park',
  'Borondo',
  'Braco Dimitrijevic',
  'Brian Coleman',
  'Brigitte Bauer',
  'Bruno Carbonnet',
  'Bruno Peinado',
  'Byoung-tak Moon',
  'Bård Breivik',
  'Béatrice Guichard',
  'Cal-Earth',
  'Cao Guimarães',
  'Carel Visser',
  'Carmelo Zagari',
  'Carole Benzaken',
  'Caroline Lee',
  'Caroline Molusson',
  'Catherine Beloeil',
  'Chaos Computer Club',
  'Charles Correia',
  'Charles Daudelin',
  'Charles Gianferrari',
  'Charles Ross',
  'Charles-Auguste Lebourg',
  'Charlie Skubich',
  'Charlie Youle',
  'Charlotte Pringuey Cessac',
  'Charwei Tsai',
  'Chen Zhen',
  'Chris Booth',
  'Christian Boltanski',
  'Christian Lapie',
  'Christian Renonciat',
  'Christine Canetti',
  'Christine O\'Loughlin',
  'Christophe Berdaguer',
  'Christophe Bodinier',
  'Christophe Cuzin',
  'Christophe Doucet',
  'Christophe Gonnet',
  'Christophe Hamaide-Pierson',
  'Christophe Jacquet (Toffe)',
  'Christophe Le François',
  'Chérif Kebbal',
  'Cildo Meireles',
  'Claes Oldenburg',
  'Claes Oldenburg et Coosje van Bruggen',
  'Claire Chevrier',
  'Claire Chevrier et Patrick Tosani',
  'Claire de Rougemont',
  'Claire Roudenko-Bertin',
  'Clara Halter',
  'Claude Boullevraye de Passillé',
  'Claude Closky',
  'Claude Courtecuisse',
  'Claude Lévêque',
  'Claude Rutault',
  'Claude Viallat',
  'Claude Viseux',
  'Claudia Comte',
  'Claudie laks',
  'Clément Laigle',
  'Concept Plastique',
  'Constantin Brâncuși',
  'Coosje van Bruggen',
  'Costas Coulentianos',
  'Cristina Iglesias',
  'Cyprien Gaillard',
  'Cyrille André',
  'Cécile Bart',
  'Cécile Daladier',
  'Céleste Boursier-Mougenot',
  'César',
  'Côme Mosta-Heirt',
  'DaBro',
  'Damien Cabanes',
  'Damien Chivialle',
  'Damien Deroubaix',
  'Dan Graham',
  'Dani Karavan',
  'Daniel Buren',
  'Daniel Chester French',
  'Daniel Coulet',
  'Daniel Denise',
  'Daniel Dezeuze',
  'Daniel Nadaud',
  'Daniel Pommereulle',
  'Daniel Pontoreau',
  'Daniel Resal',
  'Daniel Spoerri',
  'Daniel Tremblay',
  'David Boeno',
  'David de Tscharner',
  'David Dubois',
  'David Hammons',
  'David Mach',
  'David Nash',
  'David Rabinowitch',
  'David Renaud',
  'David Soussana',
  'Delo Lindo',
  'Delphine Bretesché',
  'Denis Darzacq',
  'Denis Godefroy',
  'Denis Malbos',
  'Denis Morog',
  'Denis Oudendijk',
  'Denis Pondruel',
  'Denis PUGNERE',
  'Denis Santachiara',
  'Dennis Adams',
  'Descatoire',
  'Diadji Diop',
  'Didier Béquillard',
  'Didier Courbot',
  'Didier Marcel',
  'Didier Tallagrand',
  'Didier Trenet',
  'Dominique Bailly',
  'Dominique Blais',
  'Dominique Gutherz',
  'Dominique Labauvie',
  'Dominique Petitgand',
  'Dorothy Cross',
  'Douglas White',
  'Dré Wapenaar',
  'Edgar Pillet',
  'Edgard Pillet',
  'Eduardo Chillida',
  'Edward Allington',
  'Edwin van der Heide',
  'Ehren Tool',
  'Eko Prawoto',
  'Elger Esser',
  'Elisa Fantozzi',
  'Elizabeth Foyé',
  'Elizabeth Guyon',
  'Ellsworth Kelly',
  'Elsa Sahal',
  'Elvire Jan',
  'Emily Young',
  'Emmanuel Perrin',
  'Emmanuel Saulnier',
  'Emmanuelle Lainé',
  'Emmanuelle Villard',
  'Erik Dietman',
  'Erik Nussbicker',
  'Ernest Pignon-Ernest',
  'Ernesto Neto',
  'Ernesto Sartori',
  'Ernst Amelung',
  'Ernst Caramelle',
  'Erró',
  'Ervin Patkaï',
  'Erwin Patkaï',
  'Erwin Wurm',
  'Estefanía Peñafiel Loaiza',
  'Etienne Bossut',
  'Ettore Spalletti',
  'Eugène Dodeigne',
  'Eugène Van Lamsweerde',
  'Eunhee Choo',
  'Evariste Richer',
  'Fabien Lerat',
  'Fabrice Hyber',
  'Faust Cardinali',
  'Felice Varini',
  'Fernand Léger',
  'Fernando Costa',
  'Florence Doléac',
  'Florentijn Hofman',
  'Florentine Guédon',
  'Florian Lechner',
  'Folkert de Jong',
  'France Siptrott',
  'Francesca Caruana',
  'Francis Burette',
  'Francis Pellerin',
  'Franz West',
  'François Azambourg',
  'François Bauchet',
  'François Bouillon',
  'François Delagnes',
  'François Fabrizi',
  'François Genot',
  'François Génot',
  'François Morellet',
  'François Méchain',
  'François Perrodin',
  'François Rouan',
  'François Stahly',
  'François-Xavier Lalanne',
  'Françoise Crémel',
  'Françoise Maire',
  'Françoise Quardon',
  'Françoise Vergier',
  'Frédéric Auguste Bartholdi',
  'Frédéric Jaudon',
  'Frédéric Ruyant',
  'Frédérique Lecerf',
  'Fujiko Nakaya',
  'Gabrielle Conilh De Beyssac',
  'Gaetano Pesce',
  'Garouste et Bonetti',
  'Gaston Lachaise',
  'Gaston-Henri Delaune',
  'Gavin Bryars',
  'Gediminas Urbonas',
  'Gelitin',
  'Geneviève Asse',
  'Geneviève Asse et Olivier Debré',
  'Georg Baselitz',
  'Georg Ettl',
  'George Rickey',
  'Georges Adilon',
  'Georges Jeanclos',
  'Georges Mathieu',
  'Georges Nadal',
  'Georges Salendre',
  'Gerlinde Frommherz',
  'Ghada Amer',
  'Gilbert Della Noce',
  'Gilles Aillaud',
  'Gilles Clément',
  'Gilles Ebersolt',
  'Gilles Roussi',
  'Gilles Roussi et Jean-Marc Steyart',
  'Gilles Touyard',
  'Gina Pane',
  'Gino de Dominicis',
  'Giuseppe Penone',
  'Gloria Friedmann',
  'Gottfried Honegger',
  'Grout et Mazéas',
  'Guillaume Bijl',
  'Guillaume Bottazzi',
  'Guillaume Castel',
  'Guillaume Leblon',
  'Guillaume Pilet',
  'GULK',
  'Gunda Förster',
  'Gustave Eiffel',
  'Gustave Moreau',
  'Guy de Rougemont',
  'Guy Lartigue',
  'Guy-Rachel Grataloup',
  'Gérald Collot',
  'Gérard Collin-Thiébaut',
  'Gérard Fromanger',
  'Gérard Garouste',
  'Gérard Serre',
  'Haim Kern',
  'Hans-Walter Müller',
  'Henri Cueco',
  'Henri de Miller',
  'Henri Larrière',
  'Henri Laurens',
  'Henri Matisse',
  'Henry Moore',
  'Herman de Vries',
  'Hervé Audouard',
  'Hervé di rosa',
  'Hervé Mathieu-Bachelot',
  'Hideaki Idetsuki',
  'Hiroshi Teshima',
  'Holger Trülzsch',
  'Honoré δ\'O',
  'Horia Damian',
  'Hreinn Friðfinnsson',
  'Huang Yong Ping',
  'Hubert Duprat',
  'Hugues Siptrott',
  'Hulda Hákon',
  'Humus',
  'Hélène Gauthier',
  'Hélène Mugot',
  'Ian Hamilton Finlay',
  'Ibaï Hernandorena',
  'IFP',
  'Igor Mitoraj',
  'Ilio Signori',
  'Ilya Iossifovich Kabakov',
  'Inge Mahn',
  'Inghild Karlsen',
  'Ingo Maurer',
  'Ingrid Luche',
  'Intégral Ruedi Baur et associés',
  'Invader',
  'Ipoustéguy',
  'Ivan Loubennikov',
  'Ivan Messac',
  'Ivan Theimer',
  'Jace',
  'Jacqueline Nicolle',
  'Jacques Bony',
  'Jacques Canonici',
  'Jacques Hondelatte',
  'Jacques Monestier',
  'Jacques Perreaut',
  'Jacques Vieille',
  'Jacques Villeglé',
  'Jacques-Victor André',
  'James Lee Byars',
  'James Turrell',
  'Jan Dibbets',
  'Jan Fabre',
  'Jan Håfström',
  'Jan Vercruysse',
  'Jan Voss',
  'Janet Cardiff',
  'Jannecke Lønne Christiansen',
  'Jasper Morrison',
  'Jaume Plensa',
  'Jean Amado',
  'Jean Arp',
  'Jean Barral-Baron',
  'Jean Bazaine',
  'Jean Carlus',
  'Jean Clareboudt',
  'Jean Denant',
  'Jean Dubuffet',
  'Jean François Gavoty',
  'Jean Gorin',
  'Jean Jullien',
  'Jean Laugier dit Beppo',
  'Jean Le Gac',
  'Jean Le Moal',
  'Jean Lurçat',
  'Jean Messagier',
  'Jean Pierre Raynaud',
  'Jean Piton',
  'Jean Prouvé',
  'Jean Ricardon',
  'Jean Roulland',
  'Jean Tinguely',
  'Jean Villemin',
  'Jean Wary',
  'Jean-André Cante',
  'Jean-Charles Blais',
  'Jean-Charles Blanc',
  'Jean-Charles de Castelbajac',
  'Jean-Claude Mayo',
  'Jean-Daniel Berclaz',
  'Jean-François Brun',
  'Jean-François Cantin',
  'Jean-François Chevalier',
  'Jean-Gabriel Coignet',
  'Jean-Jacques Dumont',
  'Jean-Louis Hurlin',
  'Jean-Luc Courcoult',
  'Jean-Luc Moulène',
  'Jean-Luc Verna',
  'Jean-Luc Vilmouth',
  'Jean-Marc Bustamante',
  'Jean-Marc De Pas',
  'Jean-Marc Steyart',
  'Jean-Marie Appriou',
  'Jean-Marie Krauth',
  'Jean-Marie Pirot',
  'Jean-Max Albert',
  'Jean-Michel Alberola',
  'Jean-Michel Meurice',
  'Jean-Michel Othoniel',
  'Jean-Michel Sanejouand',
  'Jean-Paul Chambas',
  'Jean-Pierre Bertrand',
  'Jean-Pierre Bourquin',
  'Jean-Pierre Brazs',
  'Jean-Pierre Filippi',
  'Jean-Pierre Pincemin',
  'Jean-Yves Brélivet',
  'Jean-Yves Lechevallier',
  'Jef Aérosol',
  'Jennifer Caubet',
  'Jenny Holzer',
  'Jeppe Hein',
  'Jesús-Rafael Soto',
  'JF Cantin',
  'Jimmie Durham',
  'Jiménez Deredia',
  'Jin Hasegawa',
  'Joan Crous',
  'Joan Fontcuberta',
  'Joan Miró',
  'Joaquín García Donaire',
  'Jochen Gerz',
  'Jodi',
  'Joel Shapiro',
  'John Armleder',
  'John Davies',
  'John Körmeling',
  'John M Armleder',
  'Johnny Hawkes',
  'Jon Rafman',
  'Jonathan Borofsky',
  'Jorge Soler',
  'Jose Pini',
  'Josep-Maria Martín',
  'Joseph Beuys',
  'Joseph Kosuth',
  'Joséphine Chevry',
  'Joël Hubaut',
  'Joël Thépault',
  'Joëlle Tuerlinckx',
  'JR',
  'Juan Soriano',
  'Judith Bartolani',
  'Jules Guissart',
  'Julia Cottin',
  'Julian Charrière',
  'Julian Opie',
  'Julien Nédélec',
  'Julien Perraud',
  'Julije Knifer',
  'Julio Silva',
  'Julius Popp',
  'Jun Honma',
  'Junko Hiroshige',
  'Jérôme Basserode',
  'Jörn Pfab',
  'Kader Attia',
  'Kaoru Muraki',
  'Karel',
  'Karel Appel',
  'Kari Cavén',
  'Karina Bisch',
  'Karl-Jean Longuet',
  'Karl-Jean LonguetL',
  'Katarína Kúdelová',
  'Kate Blacker',
  'Katerine Louineau',
  'Katsuhito Nishikawa',
  'Kazys Venclovas',
  'Keith Haring',
  'Keith Sonnier',
  'Kengo Kuma',
  'Kevin van Braak',
  'Kidlat Tahimik',
  'Kim Hamisky',
  'Kinya Maruyama',
  'Kjell Erik Killi Olsen',
  'Klaus Heid',
  'Klaus Rinke',
  'Kleber Matheus',
  'Koji Nakase',
  'Koji Yamamoto',
  'Konrad Loder',
  'Konstantinos Dimitriadis',
  'Krijn de Koning',
  'Kristian Gavoille',
  'Kristján Guðmundsson',
  'L\'Atlas',
  'Lang et Baumann',
  'Lara Almarcegui',
  'Laura Lamiel',
  'Laurence De Leersnyder',
  'Laurent Baude',
  'Laurent Fétis',
  'Laurent Kropf',
  'Laurent Le Deunff',
  'Laurent Massaloux',
  'Laurent Moriceau',
  'Laurent Pariente',
  'Laurent Pernot',
  'Laurent Saksik',
  'Lawrence Weiner',
  'Leander Djønne',
  'Leandro Erlich',
  'Lehna Edwall',
  'Leonardo Delfino',
  'Les Frères Chapuisat',
  'Liliana de Vito',
  'Liliana Moro',
  'Liliana Motta',
  'Lim Dong-lak',
  'Linda Covit',
  'Lionel Sabatté',
  'Lita Albuquerque',
  'Liu Bolin',
  'Liuba Kirova',
  'Lois Weinberger',
  'Lorentino',
  'Lorraine Pellegrini',
  'Los Carpinteros',
  'Louis Derbré',
  'Louis Holweck',
  'Louis Leygue',
  'Louis Madeline',
  'Louis Rey',
  'Louis-Ernest Barrias',
  'Louis-Robert Muller',
  'Louise Bourgeois',
  'Lovato',
  'Luc Doerflinger',
  'Luc-Simon',
  'Luciano Fabro',
  'Lucien Fontanarosa',
  'Lucien Lautrec',
  'Ludger Gerdes',
  'Luigi Guardigli',
  'Lydie Arickx',
  'Lydie Chauvac',
  'Léon-Ernest Drivier',
  'Léonardo Delfino',
  'Maarten Van Severen',
  'Maarten Vanden Eynde',
  'Maciej Albrzykowski',
  'Made',
  'Maki Kijima',
  'Manfred Pernice',
  'Marc Chagall',
  'Marc Couturier',
  'Marc Fornès',
  'Marc-Camille Chaimowicz',
  'Marek Borsányi',
  'Maria Nordman',
  'Marie Denis',
  'Marie Drouet',
  'Marie Péjus',
  'Marie-Ange Guilleminot',
  'Marie-Christine Dorner',
  'Marie-Françoise Radovic Douillard',
  'Marin Kasimir',
  'Marina Abramović',
  'Marina Le Gall',
  'Marino di Teana',
  'Mario Botta',
  'Mario Merz',
  'Marion Verboom',
  'Mark di Suvero',
  'Mark Dion',
  'Mark Handforth',
  'Markus Raetz',
  'Marta Colvin',
  'Martial Raysse',
  'Martin Barré',
  'Martin Gracineau',
  'Martin Szekely',
  'Martti Aiha',
  'Martín Ruiz de Azúa',
  'Marylène Négro',
  'Masahiro Kiyomizu',
  'Masaki Fujihata',
  'Masaya Shibayama',
  'Matali Crasset',
  'Matias Faldbakken',
  'Matouš Lipus',
  'Matthieu Pilaud',
  'Mattia Bonetti',
  'Maurice Chaudière',
  'Maurizio Nannucci',
  'Mauro Corda',
  'Max Ernst',
  'Max Laigneau',
  'Maxime Descombin',
  'Mehmet Ali Uysal',
  'Melik Ohanian',
  'Meret Oppenheim',
  'Micha Laury',
  'Michael Beutler',
  'Michael Craig Martin',
  'Michael Heizer',
  'Michael Noble',
  'Michel Blazy',
  'Michel Charpentier',
  'Michel Deverne',
  'Michel Dufresne',
  'Michel François',
  'Michel Gérard',
  'Michel Paysant',
  'Michel Poix',
  'Michel Verjux',
  'Michelangelo Pistoletto',
  'Michelle Lopez',
  'Michiyoshi Isozaki',
  'Michèle Blondel',
  'Michèle Forgeois',
  'Michèle Schneider',
  'Mick Peter',
  'Miguel Berrocal',
  'Miguel Chevalier',
  'Miguel-Angel Molina',
  'Morgane Tschiember',
  'Mrzyk & Moriceau',
  'Mustapha Sanaoui',
  'Mustapha Sanaoui et Nathalie Dubois',
  'Myriam Mechita',
  'Nadia Lichtig',
  'Nancy Holt',
  'Nancy Rubins',
  'Nancy Wilson-Pajic',
  'Natacha Lesueur',
  'Nathalie Bles',
  'Nathalie Dubois',
  'Nathalie Talec',
  'Nayel Zeaiter',
  'Nicolas Boulard',
  'Nicolas Chenard',
  'Nicolas Chénard',
  'Nicolas Fedorenko',
  'Nicolas Floc\'h',
  'Nicolas Rouxel-Chaurey',
  'Nicolas Schneider',
  'Nicolas Schöffer',
  'Niele Toroni',
  'Niki de Saint Phalle',
  'Niki de Saint Phalle et Jean Tinguely',
  'Niklaus Thoenen',
  'Nikolay Polissky',
  'Nissim Merkado',
  'Noel Varoqui',
  'Noël Dolla',
  'Nøne Futbol Club',
  'Observatorium',
  'Octave Simon',
  'Oddvar I.N.',
  'Olgga architectes',
  'Olivier Agid',
  'Olivier Debré',
  'Olivier Gagnère',
  'Olivier Mosset',
  'Olivier Sidet',
  'On Kawara',
  'Orlan',
  'Oscar Estruga',
  'Oscar Niemeyer',
  'Ossip Zadkine',
  'Oulipo',
  'Pablo Garcia',
  'Pablo Picasso',
  'Paola Pivi',
  'Paolo Grassino',
  'Parvine Curie',
  'Pascal Bernier',
  'Pascal Brateau',
  'Pascal Convert',
  'Pascal Mourgue',
  'Pascale Marthine Tayou',
  'Pascale Mijares',
  'Patrice Alexandre',
  'Patrice Carré',
  'Patrice Lemarié',
  'Patricia d\'Isola',
  'Patricia d\'Isola - Christophe Lefrançois - Katerine Louineau',
  'Patrick Bailly-Maître-Grand',
  'Patrick Blanc',
  'Patrick Bouchain',
  'Patrick Corillon',
  'Patrick Dougherty',
  'Patrick Faigenbaum',
  'Patrick Jouin',
  'Patrick Poirier',
  'Patrick Raynaud',
  'Patrick Saytour',
  'Patrick Tosani',
  'Patxi Xabier Lezama Perier',
  'Paul Belmondo',
  'Paul Bony',
  'Paul Flury',
  'Paul Griot',
  'Paul Rebeyrolle',
  'Paul-Armand Gette',
  'Pauline Daniel',
  'Pavel Schmidt',
  'Per Barclay',
  'Per Inge Bjørlo',
  'Per Kirkeby',
  'Peter Briggs',
  'Peter Downsbrough',
  'Peter Stämpfli',
  'Petit',
  'Philippe Berry',
  'Philippe Cazal',
  'Philippe Cognée',
  'Philippe Favier',
  'Philippe Garel',
  'Philippe Lang',
  'Philippe Poupet',
  'Philippe Richard',
  'Philolaos',
  'Pierre Alechinsky',
  'Pierre Ardouvin',
  'Pierre Bernard',
  'Pierre Bismuth',
  'Pierre Buraglio',
  'Pierre Charpin',
  'Pierre di Sciullo',
  'Pierre Joseph',
  'Pierre Mabille',
  'Pierre Manoli',
  'Pierre Monjaret',
  'Pierre Peignot',
  'Pierre Sabatier',
  'Pierre Soulages',
  'Pierre Székely',
  'Pierre Theunissen',
  'Pierre Tual',
  'Pierre Zvenigorodski',
  'Pierre-Albert Célice',
  'Pierre-Alexandre Rémy',
  'Pierre-André Dufetel',
  'Pierre-Noël Drain',
  'Pierrick Sorin',
  'Piotr Kowalski',
  'Pol Bury',
  'Polska',
  'Péixe Collardot',
  'Rachid Khimoune',
  'Rafael Lain',
  'Raffael Rheinsberg',
  'Rainer Gross',
  'Raoul Marek',
  'Raoul Ubac',
  'Rasheed Araeen',
  'Raymond Mason',
  'Raymond Moretti',
  'Raymond Subes',
  'Rebecca Horn',
  'Rebecca Warren',
  'Reinout d\'Haese',
  'Remy Zaugg',
  'René Collamarini',
  'Richard Baquié',
  'Richard Deacon',
  'Richard Long',
  'Richard Nonas',
  'Richard Serra',
  'Richard Wilson',
  'Rivane Neuen-Schwander',
  'Robert Julius Jacobsen',
  'Robert Morris',
  'Robert Smithson',
  'Robert Stadler',
  'Roger Gaudreau',
  'Roger Tallon',
  'Roger-Henri Expert',
  'Roland Cognet',
  'Rolf Julius',
  'Roman Opalka',
  'Roman Signer',
  'Ronan et Erwan Bouroullec',
  'Roselyne Gravand',
  'Roy Lichtenstein',
  'Ruedi Baur',
  'Ruedi Baur et Eric Jourdan',
  'Rugerro Pazzi',
  'Rut Blees Luxemburg',
  'Ryszard Litwiniuk',
  'Régine Raphoz',
  'Sabina Lang Daniel Baumann',
  'Sabine Zaalene',
  'Saburo Muraoka',
  'Salvador Dalí',
  'Samuel Buckman',
  'Sanaz Azari',
  'Sandrine Pelletier',
  'Sandro Chia',
  'Sara Holt',
  'Sarah Sze',
  'Sarah Tritz',
  'Sarkis',
  'Sarkis Zabunyan',
  'Saâdane Afif',
  'Serge Homs',
  'Serge Landois',
  'Serge Stephan',
  'Sesostris Vitullo',
  'Setsuko Nagasawa',
  'Shelomo Selinger',
  'Shintaro Tanaka',
  'Shirley Jaffe',
  'Siah Armajani',
  'Sigurður Guðmundsson',
  'Simon Bernheim',
  'Sissel Tolaas',
  'Sol LeWitt',
  'Sorel Etrog',
  'Sou Fujimoto',
  'SpY',
  'Stalker',
  'Stefan Rinck',
  'Steinar Christensen',
  'Stelios Faitakis',
  'Stephan Balkenhol',
  'Stephen Antonakos',
  'Stéphane Belzère',
  'Stéphane Buttier',
  'Stéphane Bérard',
  'Stéphane Calais',
  'Stéphane Thidet',
  'Stéphane Vigny',
  'Stéphanie Buttier',
  'Stéphanie Cherpin',
  'Sunoj D',
  'Surasi Kusolwong',
  'Sven Domann',
  'Sylvain Dubuisson',
  'Sylvia Hansmann',
  'Sylvie Blocher',
  'Sylvie Sandjian',
  'Sébastien Lacroix',
  'Sébastien Vonier',
  'Tadashi Kawamata',
  'Taiko Shono',
  'Takamasa Kuniyasu',
  'Takis',
  'Takuro Osaka',
  'Tamaze Kalandadze',
  'Tang Da Wu',
  'Tania Mouraud',
  'Tanya Preminger',
  'Tatsuji Ushijima',
  'Tatsuo Inagaki',
  'Tatsuo Kawaguchi',
  'Tatzu Nishi',
  'Tav Group',
  'Tchang',
  'Terje Ojaver',
  'Teruhisa SUZUKI',
  'Teruhisa Suzuki',
  'Tetsuo Sekine',
  'The User',
  'Thierry Devaux',
  'Thierry Lahontâa',
  'Thomas Grünfeld',
  'Thomas Houseago',
  'Thomas Huot-Marchand',
  'Thomas Tilly',
  'Thu Van Tran',
  'Théo Mercier',
  'Théo Mercier et Christophe Hamaide-Pierson',
  'Théodore Fivel',
  'Tilt',
  'Tim',
  'Timothée Talard',
  'Tjeerd Alkema',
  'Tjeerd Alkema et Lydie Chauvac',
  'Tjerrie Verhellen',
  'Tom Shannon',
  'Tom Volkaert',
  'Toni Grand',
  'Tony Cragg',
  'Torao Yazaki',
  'Toshiharu Miki',
  'Toshikatsu Endo',
  'Tristan Eaton',
  'Ulrich Rückriem',
  'Valentine Schlegel',
  'Valerio Adami',
  'Valérie de Calignon',
  'Valérie Izzo',
  'Valérie Mréjen',
  'Veit Stratmann',
  'Victor Anicet',
  'Victor López González',
  'Victor Vasarely',
  'Vincent Barré',
  'Vincent Batbedat',
  'Vincent Bioulès',
  'Vincent Du Bois',
  'Vincent Ganivet',
  'Vincent Kohler',
  'Vincent Lamouroux',
  'Vincent Mauger',
  'Vincent Prud\'homme',
  'Violette Le Queré',
  'Virginie Yassef',
  'Visuel Design Jean Widmer',
  'Vladimír Škoda',
  'Vuk Ćosić',
  'Véronique Joumard',
  'Walter De Maria',
  'Waltercio Caldas',
  'Walther Piesch',
  'Wilfrid Almendra',
  'Willem de Kooning',
  'William Chattaway',
  'Winfried Baumann',
  'Wolfgang Laib',
  'Wolfgang Nestler',
  'Xavier Veilhan',
  'Yaacov Agam',
  'Yan Pei-Ming',
  'Yann de Portzamparc',
  'Yann Kersalé',
  'Yann Lestrat',
  'Yasuo Mizui',
  'Yasuyoshi Sugiura',
  'Yasuyuki Watanabe',
  'Yayoi Kusama',
  'Yolanda Gutiérrez',
  'Yona Friedman',
  'Yoshi Okuda',
  'Yoshikuni Iida',
  'Younès Rahmoun',
  'Yuan Gong',
  'Yuhsin U Chang',
  'Yves Klein',
  'Yvette Alleaume',
  'Yvette et Bernard Alleaume',
  'Zaha Hadid',
  'Zao Wou-Ki',
  'Ángel Orensanz',
  'Édouard Boyer',
  'Édouard François',
  'Élisabeth Ballet',
  'Élizabeth Garouste',
  'Émilie Perotto',
  'Éric Croes',
  'Éric Dalbis',
  'Éric Jourdan',
  'Éric Watt',
  'Étienne Cliquet',
  'Étienne Hajdu',
  'Étienne-Martin',
  'Ólafur Gíslason',
  'Štefan Papčo'
];

function api_get($parameters) {
  $parameters['format'] = "json";
  $postdata = http_build_query($parameters);

  $c = curl_init();
  curl_setopt($c, CURLOPT_URL, 'http://publicartmuseum.net/w/api.php?'.$postdata);
  curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($c, CURLOPT_HEADER, false);
  $output = curl_exec($c);

  return json_decode($output);
}

function api_v1_get($parameters) {
  $parameters['format'] = "json";
  $postdata = http_build_query($parameters);

  $c = curl_init();
  curl_setopt($c, CURLOPT_URL, 'http://publicartmuseum.net/w/api.php?'.$postdata);
  curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($c, CURLOPT_HEADER, false);
  $output = curl_exec($c);

  return json_decode($output);
}

function api_post($parameters) {

  //-- spécifie le format de réponse attendu
  $parameters['format'] = "json";
  
  //-- construit les paramètres à envoyer
  $postdata = http_build_query($parameters);
  
  //-- envoie la requête avec cURL
  $ch = curl_init();
  $cookiefile = tempnam("/tmp", "CURLCOOKIE");
  curl_setopt_array($ch, array(
    CURLOPT_COOKIEFILE => $cookiefile,
    CURLOPT_COOKIEJAR => $cookiefile,
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_POST => TRUE
  ));
  curl_setopt($ch, CURLOPT_URL, 'http://publicartmuseum.net/w/api.php');
  curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
  
  //-- envoie les cookies actuels avec curl
  $cookies = array();
  foreach ($_COOKIE as $key => $value)
    if ($key != 'Array')
      $cookies[] = $key . '=' . $value;
  curl_setopt( $ch, CURLOPT_COOKIE, implode(';', $cookies) );
  
  //-- arrête la session en cours
  session_write_close();
  
  $result = json_decode(curl_exec($ch));
  curl_close($ch);
  
  //-- redémarre la session
  session_start();
  
  return $result;

}

function get_token() {
  $result = api_post([
    "action"	=> "query",
    "meta"		=> "tokens"
  ]);

  return $result->query->tokens->csrftoken;
}

function login() {
  $user = 'François';
  $pass = 'Juillet14';
  
  //-- envoie une première requête de login
  $result = api_post([
    "action" => "login",
    "lgname" => $user,
    "lgpassword" => $pass
  ]);

  //-- si tout se passe bien, l'api renvoie un token de connexion à lui retransmettre
  if ($result->login->result == "NeedToken") {
    if (!empty($result->login->token)) {
      $token = $result->login->token;
      $_SESSION["logintoken"] = $token;

      //-- renvoie ce token
      $result = api_post([
        "action" => "login",
        "lgname" => $user,
        "lgpassword" => $pass,
        "lgtoken" => $token
      ]);
    }
  }

  return $result;
}

function edit($page, $text) {
  $result = api_post([
    "action" => "edit",
    "title" => $page,
    "text" => $text,
    "summary" => "{{Artiste}}",
    "token" => get_token()
  ]);

  return $result;
}

function convert_artist($title) {
  $output = api_get([
    "action"	=> "query",
    "prop"		=> "revisions",
    "rvlimit" => 1,
    "rvprop"  => "content",
    "titles"  => $title,
    "continue" => ''
  ]);

  $error = false;

  ob_start();

  foreach ($output->query->pages as $page) {
    $content = $page->revisions[0]->{'*'};
    $lines = explode("\n", $content);
    print "{{Artiste\n";
    foreach ($lines as $line) {
      if ($line === "{{Artiste") {
        $content = ob_get_contents();
        ob_end_clean();
        print "<li><a href=\"http://publicartmuseum.net/wiki/" . urlencode(str_replace(' ', '_', $title)) . "\">" . $title . "</a> : déjà converti</li>\n";
        return;
      }
      if (preg_match('/^[^=]+=".*"$/', $line)) {
        $key = preg_replace('/^([^=]+)=".*$/', '$1', $line);
        if ($key == 'q')
          $key = 'wikidata';
        $value = preg_replace('/^[^=]+="(.*)"$/', '$1', $line);
        $value = preg_replace('/,[\s]*$/', '', $value);
        if ($value !== '')
          print "|" . $key . "=" . $value . "\n";
      }
    }
    print "}}";
  }

  $content = ob_get_contents();
  ob_end_clean();


  if ($content != "Erreur") {
    $result = edit($title, $content);
    print "<li><a href=\"http://publicartmuseum.net/wiki/" . urlencode(str_replace(' ', '_', $title)) . "\">" . $title . "</a> : " . $result->edit->result . "</li>\n";
    file_put_contents('./convert.log', $title . "\t" . $result->edit->result . PHP_EOL, FILE_APPEND);
  } else {
    print "<li><a href=\"http://publicartmuseum.net/wiki/" . urlencode(str_replace(' ', '_', $title)) . "\">" . $title . "</a> : erreur</li>\n";
    file_put_contents('./convert.log', $title . "\t" . "Erreur" . PHP_EOL, FILE_APPEND);
  }

}

login();

print '<ul>';

$start = 1000;
$width = 50;

for ($i = 0; $i < $width && $start + $i < sizeof($artists); $i++) {
  convert_artist($artists[$start + $i]);
}

print '</ul>';
