<?php
# This file was automatically generated by the MediaWiki 1.21.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# DEBUG
//error_reporting( -1 );
//ini_set( 'display_startup_errors', 1);
//ini_set( 'display_errors', 1 );
/*
 $wgShowExceptionDetails=true;
 $wgShowDebug=true;
 $wgDevelopmentWarnings=true;  

$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
 $wgDebugComments = true;
*/

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "atlasmuseum";
$wgMetaNamespace = "Atlasmuseum";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://publicartmuseum.net";
#$wgServer = "http://www.atlasmuseum.net";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/wiki.png";

$wgFavicon = "$wgScriptPath/skins/common/images/favicon.ico";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@publicartmuseum.net";
$wgPasswordSender = "apache@publicartmuseum.net";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "mysql51-82.bdb";
$wgDBname = "publicarmod1";
$wgDBuser = "publicarmod1";
$wgDBpassword = "1dwy2Myi";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "fr";

$wgSecretKey = "0d876bb38051b2061cc068e94d192f950bb30f012ebbfc5a1084a42209009f41";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "b8dc724ce3cc6ba5";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
    $wgValidSkinNames=array("vector", "atlasmuseum");
$wgDefaultSkin = "atlasmuseum";
$wgSkipSkins = array("chick", "cologneblue", "nostalgia", "simple", "standard", "monobook");
$wgHiddenPrefs[] = 'skin';
//$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

## S'il faut utiliser des informations détaillées de droits d'auteur lors du téléversement de fichiers
$wgUseCopyrightUpload = true;

## S'il faut vérifier les informations de droits d'auteur lors du téléversement de fichiers
$wgCheckCopyrightUpload = true;

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['Read'] = true;

// Permissions specific to logged-in accounts (user)
$wgGroupPermissions['user' ]['move']            = false;
$wgGroupPermissions['user' ]['read']            = true;
$wgGroupPermissions['user' ]['edit']            = true;
$wgGroupPermissions['user' ]['createpage']      = true;
$wgGroupPermissions['user' ]['createtalk']      = true;
$wgGroupPermissions['user' ]['upload']          = true;
$wgGroupPermissions['user' ]['reupload']        = true;
$wgGroupPermissions['user' ]['reupload-shared'] = true;
$wgGroupPermissions['user' ]['minoredit']       = true;
$wgGroupPermissions['user' ]['purge']           = false; // can use ?action=purge without clicking "ok"

# End of automatically generated settings.
# Add more configuration options below.


require_once "$IP/skins/atlasmuseum/ressources.php";
require_once "$IP/extensions/ConfirmEdit/ConfirmEdit.php";
require_once "$IP/extensions/Gadgets/Gadgets.php";
require_once "$IP/extensions/Nuke/Nuke.php";
require_once "$IP/extensions/ParserFunctions/ParserFunctions.php";

require_once "$IP/extensions/Renameuser/Renameuser.php";
require_once "$IP/extensions/Vector/Vector.php";
require_once "$IP/extensions/WikiEditor/WikiEditor.php";
// Enables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
 
// Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 1;
 
// Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 1;

require_once "$IP/extensions/Widgets/Widgets.php";
require_once "$IP/extensions/AdminLinks/AdminLinks.php";
require_once "$IP/extensions/Arrays/Arrays.php";
require_once "$IP/extensions/DataTransfer/DataTransfer.php";
require_once "$IP/extensions/HeaderTabs/HeaderTabs.php";
require_once "$IP/extensions/PageSchemas/PageSchemas.php";
require_once "$IP/extensions/ReplaceText/ReplaceText.php";
/*
require_once "$IP/extensions/ConfirmEdit/ReCaptcha.php";
$wgCaptchaClass = 'ReCaptcha';
$wgReCaptchaPublicKey = 'your public key here';
$wgReCaptchaPrivateKey = 'your private key here';
*/

require_once "$IP/extensions/Collection/Collection.php";
$wgGroupPermissions['user']['collectionsaveascommunitypage'] = true;
$wgGroupPermissions['user']['collectionsaveasuserpage'] = true;

require_once  "$IP/extensions/SemanticBundle/SemanticBundleSettings.php";
require_once  "$IP/extensions/SemanticBundle/SemanticBundle.php";

include_once("$IP/extensions/SemanticDrilldown/SemanticDrilldown.php");
$sdgFiltersSmallestFontSize=9;
$sdgFiltersLargestFontSize=25;
$sdgNumResultsPerPage=250;


require_once  "$IP/extensions/Maps/Maps.php";
$wgMaxShellMemory = 512000;
$wgMemoryLimit = "64M";

$smwgQMaxSize=15;


$wgHooks['SkinTemplateOutputPageBeforeExec'][] = 'lfTOSLink';
function lfTOSLink( $sk, &$tpl ) {
	$tpl->set( 'apropos', $sk->footerLink( 'apropos', 'apropospage' ) );
	$tpl->set( 'avertissement', $sk->footerLink( 'avertissement', 'avertissementpage' ) );
	$tpl->set( 'legal', $sk->footerLink( 'legal', 'legalpage' ) );
	$tpl->set( 'contact', $sk->footerLink( 'contact', 'contactpage' ) );
        unset( $tpl->data['footerlinks']['places']['privacy'] );
        unset( $tpl->data['footerlinks']['places']['disclaimer'] );
	$tpl->data['footerlinks']['places'] = array('apropos', 'avertissement','legal', 'contact');
	return true;
}

$smwgShowFactbox = SMW_FACTBOX_NONEMPTY;

#InputBox
require_once("$IP/extensions/InputBox/InputBox.php");

require_once( "$IP/extensions/googleAnalytics/googleAnalytics.php" );
// Replace xxxxxxx-x with YOUR GoogleAnalytics UA number
$wgGoogleAnalyticsAccount = "UA-49974954-1"; 
// Optional Variables (both default to true)
$wgGoogleAnalyticsIgnoreSysops = true;
$wgGoogleAnalyticsIgnoreBots = true;
// If you use AdSense as well and have linked your accounts, set this to true to enable tracking
$wgGoogleAnalyticsAddASAC = false;

setlocale (LC_ALL, 'en_US.UTF-8');

$wgAllowCopyUploads = true;
$wgGroupPermissions['autoconfirmed']['upload_by_url'] = true;
/*
$wgFileExtensions = array_merge( $wgFileExtensions, array( 'png', 'gif', 'jpg', 'jpeg' ) );
$wgAllowJavaUploads = true;
$wgStrictFileExtensions = false;
*/

#$wgJobRunRate = 100.0;
$smwgQMaxInlineLimit = 10000;

$htEditTabLink = false;

// autorise les tags <html> &  </html> - ajouté le 1/11/15
$wgRawHtml = true;

#Semanticgraph
require_once("$IP/extensions/SemanticGraph/includes/SemanticGraph2.php");
$wgVerifyMimeType = false;

$wgSemanticGraphSettings->dotCommand = '/path/to/dot';       
$wgSemanticGraphSettings->neatoCommand = '/path/to/neato';
$wgSemanticGraphSettings->mmAppletPath = 'http://URL/to/freemind.jar';
$wgSemanticGraphSettings->maxToDispUnfolded = 10; 
//when displaying a // freemind map by default any branch with more than 10 items starts folded // this can be overridden by the fold=none|level1|level2|level3|large option

$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgShowDBErrorBacktrace = true;

require_once("$IP/extensions/PHPExcel/PHPExcel.php");
$srfgFormats[] = 'excel';
#$sdgMinValuesForComboBox=5000;
