<?php

class Constants {

  public static function get_domains() {
    return [
      [ 'label' => 'aménagement paysager', 'id' => '' ],
      [ 'label' => 'anamorphose', 'id' => 'Q217422' ],
      [ 'label' => 'architecture', 'id' => 'Q12271' ],
      [ 'label' => 'architecture intérieure', 'id' => '' ],
      [ 'label' => 'arts graphiques', 'id' => 'Q911059' ],
      [ 'label' => 'art sonore', 'id' => 'Q1744327' ],
      [ 'label' => 'art vidéo', 'id' => 'Q682010' ],
      [ 'label' => 'assemblage', 'id' => 'Q262343' ],
      [ 'label' => 'bas-relief', 'id' => 'Q14562306' ],
      [ 'label' => 'broderie', 'id' => 'Q18281' ],
      [ 'label' => 'collage', 'id' => 'Q170593' ],
      [ 'label' => 'compression', 'id' => '' ],
      [ 'label' => 'contre-relief', 'id' => '' ],
      [ 'label' => 'design', 'id' => 'Q82604' ],
      [ 'label' => 'design graphique', 'id' => 'Q185925' ],
      [ 'label' => 'dessin', 'id' => 'Q93184' ],
      [ 'label' => 'dispositif', 'id' => '' ],
      [ 'label' => 'environnement', 'id' => 'Q787180' ],
      [ 'label' => 'fontaine', 'id' => 'Q483453' ],
      [ 'label' => 'fresque', 'id' => 'Q134194' ],
      [ 'label' => 'haut-relief', 'id' => 'Q5784272' ],
      [ 'label' => 'installation', 'id' => 'Q20437094' ],
      [ 'label' => 'installation audiovisuelle', 'id' => '' ],
      [ 'label' => 'installation avec de la lumière', 'id' => '' ],
      [ 'label' => 'installation avec du mouvement', 'id' => '' ],
      [ 'label' => 'installation cinématographique', 'id' => '' ],
      [ 'label' => 'installation mixte', 'id' => '' ],
      [ 'label' => 'installation multimédia', 'id' => '' ],
      [ 'label' => 'installation multimédia interactive', 'id' => '' ],
      [ 'label' => 'installation photographique', 'id' => '' ],
      [ 'label' => 'installation sonore', 'id' => '' ],
      [ 'label' => 'installation vidéo', 'id' => '' ],
      [ 'label' => 'livre', 'id' => 'Q571' ],
      [ 'label' => 'mobile', 'id' => 'Q784445' ],
      [ 'label' => 'mobilier', 'id' => 'Q14745' ],
      [ 'label' => 'moquette', 'id' => 'Q29167278' ],
      [ 'label' => 'mosaïque', 'id' => '' ],
      [ 'label' => 'nouveaux médias', 'id' => 'Q683794' ],
      [ 'label' => 'objet', 'id' => 'Q337060' ],
      [ 'label' => 'œuvre cinétique', 'id' => 'Q466521' ],
      [ 'label' => 'œuvre en 3 dimensions', 'id' => '' ],
      [ 'label' => 'œuvre textile', 'id' => 'Q22075301' ],
      [ 'label' => 'papier peint', 'id' => 'Q191529' ],
      [ 'label' => 'peinture', 'id' => 'Q3305213' ],
      [ 'label' => 'peinture murale', 'id' => 'Q219423' ],
      [ 'label' => 'photographie', 'id' => 'Q125191' ],
      [ 'label' => 'photomontage', 'id' => 'Q828107' ],
      [ 'label' => 'publication', 'id' => '' ],
      [ 'label' => 'ready-made', 'id' => 'Q732577' ],
      [ 'label' => 'relief', 'id' => 'Q245117' ],
      [ 'label' => 'revêtement de sol', 'id' => 'Q1433006' ],
      [ 'label' => 'rideau', 'id' => 'Q49005' ],
      [ 'label' => 'ronde-bosse', 'id' => 'Q2520013' ],
      [ 'label' => 'sculpture', 'id' => 'Q860861' ],
      [ 'label' => 'sculpture modulaire', 'id' => '' ],
      [ 'label' => 'sculpture monumentale', 'id' => 'Q3476533' ],
      [ 'label' => 'signalétique', 'id' => 'Q30337832' ],
      [ 'label' => 'stabile', 'id' => '' ],
      [ 'label' => 'tapis', 'id' => 'Q163446' ],
      [ 'label' => 'tapisserie', 'id' => 'Q184296' ],
      [ 'label' => 'vêtement', 'id' => 'Q11460' ],
      [ 'label' => 'vitrail', 'id' => 'Q1473346' ]
    ];
  }

  public static function get_colors() {
    return [
      [ 'label' => 'argent', 'id' => 'Q317802' ],
      [ 'label' => 'aubergine', 'id' => 'Q1403218' ],
      [ 'label' => 'azur', 'id' => 'Q373058' ],
      [ 'label' => 'beige', 'id' => 'Q843607' ],
      [ 'label' => 'bitume', 'id' => '' ],
      [ 'label' => 'blanc', 'id' => 'Q23444' ],
      [ 'label' => 'bleu', 'id' => 'Q1088' ],
      [ 'label' => 'bordeaux', 'id' => 'Q10859033' ],
      [ 'label' => 'brique', 'id' => '' ],
      [ 'label' => 'bronze', 'id' => 'Q2778382' ],
      [ 'label' => 'chair', 'id' => '' ],
      [ 'label' => 'cuivre', 'id' => 'Q2722041' ],
      [ 'label' => 'cyan', 'id' => 'Q180778' ],
      [ 'label' => 'ébène', 'id' => '' ],
      [ 'label' => 'fer', 'id' => '' ],
      [ 'label' => 'gris', 'id' => 'Q42519' ],
      [ 'label' => 'gris acier', 'id' => '' ],
      [ 'label' => 'ivoire', 'id' => 'Q1358981' ],
      [ 'label' => 'jaune', 'id' => 'Q943' ],
      [ 'label' => 'kaki', 'id' => 'Q650770' ],
      [ 'label' => 'magenta', 'id' => 'Q3276756' ],
      [ 'label' => 'marron', 'id' => 'Q47071' ],
      [ 'label' => 'noir', 'id' => 'Q23445' ],
      [ 'label' => 'or', 'id' => 'Q208045' ],
      [ 'label' => 'orange', 'id' => 'Q39338' ],
      [ 'label' => 'pourpre', 'id' => 'Q3257809' ],
      [ 'label' => 'rose', 'id' => 'Q429220' ],
      [ 'label' => 'rouge', 'id' => 'Q3142' ],
      [ 'label' => 'sable', 'id' => 'Q9303163' ],
      [ 'label' => 'sépia', 'id' => 'Q767608' ],
      [ 'label' => 'turquoise', 'id' => 'Q5960345' ],
      [ 'label' => 'vermillon', 'id' => 'Q737438' ],
      [ 'label' => 'vert', 'id' => 'Q3133' ],
      [ 'label' => 'vert kaki', 'id' => '' ],
      [ 'label' => 'violet', 'id' => 'Q428124' ]
    ];
  }

  public static function get_materials() {
    return [
      [ 'label' => 'acier', 'id' => 'Q11427' ],
      [ 'label' => 'aluminium', 'id' => 'Q663' ],
      [ 'label' => 'animaux', 'id' => 'Q729' ],
      [ 'label' => 'bâche', 'id' => '' ],
      [ 'label' => 'basalte', 'id' => 'Q43338' ],
      [ 'label' => 'béton', 'id' => 'Q22657' ],
      [ 'label' => 'bois', 'id' => 'Q287' ],
      [ 'label' => 'brique', 'id' => 'Q40089' ],
      [ 'label' => 'bronze', 'id' => 'Q34095' ],
      [ 'label' => 'caoutchouc', 'id' => 'Q18113858' ],
      [ 'label' => 'céramique', 'id' => 'Q45621' ],
      [ 'label' => 'ciment', 'id' => 'Q45190' ],
      [ 'label' => 'coton', 'id' => 'Q11457' ],
      [ 'label' => 'cuir', 'id' => 'Q286' ],
      [ 'label' => 'cuivre', 'id' => 'Q753' ],
      [ 'label' => 'dural', 'id' => 'Q177342' ],
      [ 'label' => 'eau', 'id' => 'Q283' ],
      [ 'label' => 'émail', 'id' => 'Q213371' ],
      [ 'label' => 'encre', 'id' => 'Q127418' ],
      [ 'label' => 'enrobé', 'id' => 'Q189259' ],
      [ 'label' => 'fer', 'id' => 'Q677' ],
      [ 'label' => 'feuille d\'or', 'id' => 'Q929186' ],
      [ 'label' => 'fibre de verre', 'id' => 'Q5861' ],
      [ 'label' => 'fonte', 'id' => 'Q483269' ],
      [ 'label' => 'glassphalt', 'id' => 'Q5567187' ],
      [ 'label' => 'granit', 'id' => 'Q41177' ],
      [ 'label' => 'grès', 'id' => 'Q830894' ],
      [ 'label' => 'informatique', 'id' => 'Q21198' ],
      [ 'label' => 'inox', 'id' => 'Q172587' ],
      [ 'label' => 'laine', 'id' => 'Q42329' ],
      [ 'label' => 'laque', 'id' => 'Q11236878' ],
      [ 'label' => 'lave', 'id' => 'Q40157' ],
      [ 'label' => 'led', 'id' => 'Q25504' ],
      [ 'label' => 'lumière', 'id' => 'Q9128' ],
      [ 'label' => 'lurex', 'id' => 'Q1877666' ],
      [ 'label' => 'marbre', 'id' => 'Q40861' ],
      [ 'label' => 'métal', 'id' => 'Q11426' ],
      [ 'label' => 'minéraux', 'id' => 'Q7946' ],
      [ 'label' => 'miroir', 'id' => 'Q35197' ],
      [ 'label' => 'néon', 'id' => 'Q654' ],
      [ 'label' => 'papier', 'id' => 'Q11472' ],
      [ 'label' => 'peinture', 'id' => 'Q174219' ],
      [ 'label' => 'pierre', 'id' => 'Q22731' ],
      [ 'label' => 'pierre de lave', 'id' => '' ],
      [ 'label' => 'plastique', 'id' => 'Q11474' ],
      [ 'label' => 'plâtre', 'id' => 'Q274988' ],
      [ 'label' => 'plexiglas', 'id' => 'Q146123' ],
      [ 'label' => 'plomb', 'id' => 'Q708' ],
      [ 'label' => 'polyester', 'id' => 'Q188245' ],
      [ 'label' => 'polystyrène', 'id' => 'Q146243' ],
      [ 'label' => 'polyuréthane', 'id' => 'Q146322' ],
      [ 'label' => 'résine', 'id' => 'Q145205' ],
      [ 'label' => 'silicone', 'id' => 'Q146439' ],
      [ 'label' => 'soie', 'id' => 'Q37681' ],
      [ 'label' => 'son', 'id' => 'Q11461' ],
      [ 'label' => 'terre', 'id' => 'Q11081619' ],
      [ 'label' => 'tissu', 'id' => 'Q28823' ],
      [ 'label' => 'toile', 'id' => 'Q4259259' ],
      [ 'label' => 'végétaux', 'id' => '' ],
      [ 'label' => 'vernis', 'id' => 'Q81683' ],
      [ 'label' => 'verre', 'id' => 'Q11469' ]
    ];
  }

  public static function get_periods() {
    return [
      [ 'label' => 'art contemporain', 'id' => 'Q186030' ],
      [ 'label' => 'art moderne', 'id' => 'Q38166' ]
    ];
  }

  public static function get_movements() {
    return [
      [ 'label' => 'abstraction lyrique', 'id' => 'Q1147263' ],
      [ 'label' => 'anti-form', 'id' => 'Q20936218' ],
      [ 'label' => 'appropriation', 'id' => 'Q123305' ],
      [ 'label' => 'art ascii', 'id' => 'Q193097' ],
      [ 'label' => 'art audiovisuel', 'id' => 'Q2864581' ],
      [ 'label' => 'art brut', 'id' => 'Q594150' ],
      [ 'label' => 'art cinétique', 'id' => 'Q466521' ],
      [ 'label' => 'art conceptuel', 'id' => 'Q203209' ],
      [ 'label' => 'art concret', 'id' => 'Q10822316' ],
      [ 'label' => 'art corporel', 'id' => 'Q678649' ],
      [ 'label' => 'art en ligne', 'id' => 'Q1569950' ],
      [ 'label' => 'art en réseau', 'id' => 'Q2864643' ],
      [ 'label' => 'art environnemental', 'id' => 'Q787180' ],
      [ 'label' => 'arte povera', 'id' => 'Q576913' ],
      [ 'label' => 'art fractal', 'id' => 'Q777696' ],
      [ 'label' => 'art génératif', 'id' => 'Q1502032' ],
      [ 'label' => 'art informel', 'id' => 'Q1054254' ],
      [ 'label' => 'art in situ', 'id' => 'Q2740415' ],
      [ 'label' => 'art interactif', 'id' => 'Q2394336' ],
      [ 'label' => 'art logiciel', 'id' => 'Q2864686' ],
      [ 'label' => 'art nouveau', 'id' => 'Q34636' ],
      [ 'label' => 'art numérique', 'id' => 'Q860372' ],
      [ 'label' => 'art postal', 'id' => 'Q843393' ],
      [ 'label' => 'art psychédélique', 'id' => 'Q696160' ],
      [ 'label' => 'art robotique', 'id' => 'Q2864727' ],
      [ 'label' => 'art sacré', 'id' => 'Q2864737' ],
      [ 'label' => 'art sociologique', 'id' => 'Q2864743' ],
      [ 'label' => 'art sonore', 'id' => 'Q1744327' ],
      [ 'label' => 'art télématique', 'id' => 'Q2864759' ],
      [ 'label' => 'art transgressif', 'id' => 'Q2864753' ],
      [ 'label' => 'art urbain', 'id' => 'Q17516' ],
      [ 'label' => 'art vidéo', 'id' => 'Q682010' ],
      [ 'label' => 'bad painting', 'id' => 'Q2878528' ],
      [ 'label' => 'bauhaus', 'id' => 'Q124354' ],
      [ 'label' => 'bio-art', 'id' => 'Q2561815' ],
      [ 'label' => 'cobra', 'id' => 'Q212611' ],
      [ 'label' => 'colorfield painting', 'id' => 'Q1164982' ],
      [ 'label' => 'cubisme', 'id' => 'Q42934' ],
      [ 'label' => 'culture jamming', 'id' => 'Q1143564' ],
      [ 'label' => 'dada', 'id' => 'Q6034' ],
      [ 'label' => 'dadaïsme', 'id' => 'Q6034' ],
      [ 'label' => 'école de New York', 'id' => 'Q1972942' ],
      [ 'label' => 'école de San Francisco', 'id' => 'Q3577822' ],
      [ 'label' => 'esthétique de la communication', 'id' => 'Q3059001' ],
      [ 'label' => 'esthétique relationnelle', 'id' => 'Q2566149' ],
      [ 'label' => 'expressionnisme', 'id' => 'Q80113' ],
      [ 'label' => 'expressionnisme abstrait', 'id' => 'Q177725' ],
      [ 'label' => 'fauvisme', 'id' => 'Q166593' ],
      [ 'label' => 'figuration libre', 'id' => 'Q1391488' ],
      [ 'label' => 'figuration narrative', 'id' => 'Q3071677' ],
      [ 'label' => 'fluxus', 'id' => 'Q108908' ],
      [ 'label' => 'futurisme', 'id' => 'Q131221' ],
      [ 'label' => 'graffiti', 'id' => 'Q17514' ],
      [ 'label' => 'gutai', 'id' => 'Q1028956' ],
      [ 'label' => 'happening', 'id' => 'Q108874' ],
      [ 'label' => 'hyperréalisme', 'id' => 'Q749832' ],
      [ 'label' => 'impressionnisme', 'id' => 'Q40415' ],
      [ 'label' => 'land art', 'id' => 'Q326478' ],
      [ 'label' => 'lettrisme', 'id' => 'Q768100' ],
      [ 'label' => 'livre d\'artiste', 'id' => 'Q1062404' ],
      [ 'label' => 'lowbrow', 'id' => 'Q1784728' ],
      [ 'label' => 'massurréalisme', 'id' => 'Q2996287' ],
      [ 'label' => 'minimalisme', 'id' => 'Q173436' ],
      [ 'label' => 'néo-expressionnisme', 'id' => 'Q589655' ],
      [ 'label' => 'néo-géo', 'id' => 'Q432026' ],
      [ 'label' => 'néo-impressionnisme', 'id' => 'Q150091' ],
      [ 'label' => 'néo pop', 'id' => 'Q3347103' ],
      [ 'label' => 'net.art', 'id' => 'Q2553758' ],
      [ 'label' => 'nouveau réalisme', 'id' => 'Q276308' ],
      [ 'label' => 'nouvelle école de Leipzig', 'id' => 'Q878864' ],
      [ 'label' => 'nouvelle figuration', 'id' => 'Q60776237' ],
      [ 'label' => 'op art ou art optique', 'id' => 'Q182331' ],
      [ 'label' => 'papunya tula', 'id' => 'Q18005' ],
      [ 'label' => 'performance artistique', 'id' => 'Q213156' ],
      [ 'label' => 'pointillisme', 'id' => 'Q200034' ],
      [ 'label' => 'pop art', 'id' => 'Q134147' ],
      [ 'label' => 'postmodernisme', 'id' => 'Q47783' ],
      [ 'label' => 'scène démo', 'id' => 'Q824340' ],
      [ 'label' => 'situationisme', 'id' => '' ],
      [ 'label' => 'stuckisme', 'id' => 'Q1351977' ],
      [ 'label' => 'superflat', 'id' => 'Q1444581' ],
      [ 'label' => 'supports/surfaces', 'id' => 'Q3504923' ],
      [ 'label' => 'surréalisme', 'id' => 'Q39427' ],
      [ 'label' => 'symbolisme', 'id' => 'Q164800' ],
      [ 'label' => 'tachisme', 'id' => 'Q372600' ],
      [ 'label' => 'trans-avant-garde', 'id' => 'Q224885' ]
    ];
  }


public static function get_pmr() {
  return [
      [ 'label' => 'site accessible aux personnes à mobilité réduite', 'id' => 'Q24192067' ],
      [ 'label' => 'site non accessible aux personnes à mobilité réduite', 'id' => 'Q24192069' ],
      [ 'label' => 'je ne sais pas', 'id' => '' ]
    ];
}

public static function get_conservation() {
  return [
      [ 'label' => 'bon état', 'id' => '' ],
      [ 'label' => 'état critique', 'id' => '' ],
      [ 'label' => 'œuvre absente', 'id' => '' ],
      [ 'label' => 'œuvre en danger', 'id' => '' ],
      [ 'label' => 'œuvre vandalisée', 'id' => '' ]
    ];
}

public static function get_conservation_precision() {
  return [
      [ 'label' => 'cassures', 'id' => '' ],
      [ 'label' => 'déjections animales', 'id' => '' ],
      [ 'label' => 'éclats', 'id' => '' ],
      [ 'label' => 'empoussièrement', 'id' => '' ],
      [ 'label' => 'encrassement dû à la pollution', 'id' => '' ],
      [ 'label' => 'fentes/fissures', 'id' => '' ],
      [ 'label' => 'humidité', 'id' => '' ],
      [ 'label' => 'mousses/champignons/dépôts naturels', 'id' => '' ],
      [ 'label' => 'mutilations (vandalisme)', 'id' => '' ],
      [ 'label' => 'parties manquantes', 'id' => '' ],
      [ 'label' => 'salissures', 'id' => '' ],
      [ 'label' => 'tags', 'id' => '' ],
      [ 'label' => 'traces d\'oxydation', 'id' => '' ],
      [ 'label' => 'trous d\'insectes (infestation active)', 'id' => '' ],
      [ 'label' => 'trous d\'insectes (infestation ancienne)', 'id' => '' ],
      [ 'label' => 'usure de la surface', 'id' => '' ]
    ];
  }

}

?>